# Generated by Django 4.0.6 on 2022-07-19 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryinventory',
            name='Item_Last_Recieved',
        ),
        migrations.RemoveField(
            model_name='bakeryinventory',
            name='Item_Next_Delievery',
        ),
        migrations.RemoveField(
            model_name='bakeryinventory',
            name='Item_UUID',
        ),
        migrations.RemoveField(
            model_name='dairyinventory',
            name='Item_Last_Recieved',
        ),
        migrations.RemoveField(
            model_name='dairyinventory',
            name='Item_Next_Delievery',
        ),
        migrations.RemoveField(
            model_name='dairyinventory',
            name='Item_UUID',
        ),
        migrations.RemoveField(
            model_name='freshinventory',
            name='Item_Last_Recieved',
        ),
        migrations.RemoveField(
            model_name='freshinventory',
            name='Item_Next_Delievery',
        ),
        migrations.RemoveField(
            model_name='freshinventory',
            name='Item_UUID',
        ),
        migrations.RemoveField(
            model_name='groceryinventory',
            name='Item_Last_Recieved',
        ),
        migrations.RemoveField(
            model_name='groceryinventory',
            name='Item_Next_Delievery',
        ),
        migrations.RemoveField(
            model_name='groceryinventory',
            name='Item_UUID',
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_First_Added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Last_Received',
            field=models.DateField(default=None, verbose_name='Item was Last Received On'),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Next_Delivery',
            field=models.DateField(default=None, verbose_name='Item Will Be Received On'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_First_Added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Last_Received',
            field=models.DateField(default=None, verbose_name='Item was Last Received On'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Next_Delivery',
            field=models.DateField(default=None, verbose_name='Item Will Be Received On'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_First_Added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Last_Received',
            field=models.DateField(default=None, verbose_name='Item was Last Received On'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Next_Delivery',
            field=models.DateField(default=None, verbose_name='Item Will Be Received On'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_First_Added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Last_Received',
            field=models.DateField(default=None, verbose_name='Item was Last Received On'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Next_Delivery',
            field=models.DateField(default=None, verbose_name='Item Will Be Received On'),
        ),
    ]
