# Generated by Django 4.0.6 on 2022-07-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_item_name_bakeryinventory_itemname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryinventory',
            options={'verbose_name_plural': 'Bakery Inventory'},
        ),
        migrations.AlterModelOptions(
            name='dairyinventory',
            options={'verbose_name_plural': 'Dairy Inventory'},
        ),
        migrations.AlterModelOptions(
            name='freshinventory',
            options={'verbose_name_plural': 'Fresh Inventory'},
        ),
        migrations.AlterModelOptions(
            name='groceryinventory',
            options={'verbose_name_plural': 'Grocery Inventory'},
        ),
    ]
