# Generated by Django 4.0.6 on 2022-07-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_itemname_bakeryinventory_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Is_New',
            field=models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line'),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Is_On_Sale',
            field=models.BooleanField(default=False, verbose_name='Is This Item On Sale?'),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Price',
            field=models.IntegerField(default=0, verbose_name='Item Price'),
        ),
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Weight_Grams',
            field=models.IntegerField(default=0, verbose_name='Item Weight In Grams'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Is_New',
            field=models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Is_On_Sale',
            field=models.BooleanField(default=False, verbose_name='Is This Item On Sale?'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Price',
            field=models.IntegerField(default=0, verbose_name='Item Price'),
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Weight_Grams',
            field=models.IntegerField(default=0, verbose_name='Item Weight In Grams'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Is_New',
            field=models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Is_On_Sale',
            field=models.BooleanField(default=False, verbose_name='Is This Item On Sale?'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Price',
            field=models.IntegerField(default=0, verbose_name='Item Price'),
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Weight_Grams',
            field=models.IntegerField(default=0, verbose_name='Item Weight In Grams'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Is_New',
            field=models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Is_On_Sale',
            field=models.BooleanField(default=False, verbose_name='Is This Item On Sale?'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Price',
            field=models.IntegerField(default=0, verbose_name='Item Price'),
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Weight_Grams',
            field=models.IntegerField(default=0, verbose_name='Item Weight In Grams'),
        ),
    ]
