# Generated by Django 4.0.6 on 2022-07-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_bakeryinventory_item_is_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryinventory',
            name='Item_Price',
            field=models.FloatField(default=0.0, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='dairyinventory',
            name='Item_Price',
            field=models.FloatField(default=0.0, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='freshinventory',
            name='Item_Price',
            field=models.FloatField(default=0.0, verbose_name='Item Price'),
        ),
        migrations.AlterField(
            model_name='groceryinventory',
            name='Item_Price',
            field=models.FloatField(default=0.0, verbose_name='Item Price'),
        ),
    ]
