# Generated by Django 4.0.6 on 2022-07-21 00:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_item_amount_bakeryinventory_item_soh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryinventory',
            name='Item_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dairyinventory',
            name='Item_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freshinventory',
            name='Item_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryinventory',
            name='Item_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='assets/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bakeryinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AlterField(
            model_name='bakeryinventory',
            name='Item_SOH',
            field=models.IntegerField(default=0, verbose_name='Item Stock On Hand'),
        ),
        migrations.AlterField(
            model_name='dairyinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AlterField(
            model_name='dairyinventory',
            name='Item_SOH',
            field=models.IntegerField(default=0, verbose_name='Item Stock On Hand'),
        ),
        migrations.AlterField(
            model_name='freshinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AlterField(
            model_name='freshinventory',
            name='Item_SOH',
            field=models.IntegerField(default=0, verbose_name='Item Stock On Hand'),
        ),
        migrations.AlterField(
            model_name='groceryinventory',
            name='Item_Inventory_UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID'),
        ),
        migrations.AlterField(
            model_name='groceryinventory',
            name='Item_SOH',
            field=models.IntegerField(default=0, verbose_name='Item Stock On Hand'),
        ),
    ]
