# Generated by Django 4.0.6 on 2022-07-22 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_bakeryinventory_item_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Inventory_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID')),
                ('Item_Name', models.CharField(max_length=100, unique=True, verbose_name='Item Name')),
                ('Item_Image', models.ImageField(default='assets/S.I.M.S.png', upload_to='assets/')),
                ('Item_SOH', models.IntegerField(default=0, verbose_name='Item Stock On Hand')),
                ('Item_Price', models.FloatField(default=0.0, verbose_name='Item Price')),
                ('Item_Is_On_Sale', models.BooleanField(default=False, verbose_name='Is This Item On Sale?')),
                ('Item_Is_New', models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line')),
                ('Item_Weight_Grams', models.IntegerField(default=0, verbose_name='Item Weight In Grams')),
                ('Item_Last_Received', models.DateField(default=None, verbose_name='Item was Last Received On')),
                ('Item_Next_Delivery', models.DateField(default=None, verbose_name='Item Will Be Received On')),
                ('Item_First_Added', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fresh Inventory',
            },
        ),
        migrations.CreateModel(
            name='MeatInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Inventory_UUID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique Inventory UUID')),
                ('Item_Name', models.CharField(max_length=100, unique=True, verbose_name='Item Name')),
                ('Item_Image', models.ImageField(default='assets/S.I.M.S.png', upload_to='assets/')),
                ('Item_SOH', models.IntegerField(default=0, verbose_name='Item Stock On Hand')),
                ('Item_Price', models.FloatField(default=0.0, verbose_name='Item Price')),
                ('Item_Is_On_Sale', models.BooleanField(default=False, verbose_name='Is This Item On Sale?')),
                ('Item_Is_New', models.BooleanField(default=False, verbose_name='Is This Item a New Product / Line')),
                ('Item_Weight_Grams', models.IntegerField(default=0, verbose_name='Item Weight In Grams')),
                ('Item_Last_Received', models.DateField(default=None, verbose_name='Item was Last Received On')),
                ('Item_Next_Delivery', models.DateField(default=None, verbose_name='Item Will Be Received On')),
                ('Item_First_Added', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fresh Inventory',
            },
        ),
    ]
