# Generated by Django 4.0.6 on 2022-07-22 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_deliinventory_meatinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliinventory',
            options={'verbose_name_plural': 'Deli Inventory'},
        ),
        migrations.AlterModelOptions(
            name='meatinventory',
            options={'verbose_name_plural': 'Meat Inventory'},
        ),
    ]
