# Generated by Django 4.0.6 on 2022-07-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_deliinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='dairyinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='deliinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='freshinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='groceryinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='meatinventory',
            name='Item_Image',
            field=models.ImageField(default=None, upload_to='assets/'),
        ),
    ]
