# Generated by Django 4.0.6 on 2022-07-13 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_UUID', models.UUIDField(default=uuid.uuid5, unique=True, verbose_name='Unique ID')),
                ('Item_Name', models.CharField(max_length=100, unique=True, verbose_name='Item Name')),
                ('Item_Amount', models.IntegerField(default=0, verbose_name='Item Amount')),
                ('Item_Last_Recieved', models.DateField(verbose_name='Item was Last Recieved On')),
                ('Item_Next_Delievery', models.DateField(verbose_name='Item Will Be Recieved On')),
            ],
        ),
    ]
