# Generated by Django 4.0.6 on 2022-07-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_api', '0002_inventory_delete_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='GroceryInvetory',
        ),
    ]
