# Generated by Django 4.0.6 on 2022-07-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_bakeryinventory_item_last_recieved_and_more'),
        ('sis_api', '0004_bakeryinventory_dairyinventory_freshinventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.bakeryinventory')),
                ('Dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dairyinventory')),
                ('Fresh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.freshinventory')),
                ('Grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.groceryinventory')),
            ],
        ),
        migrations.DeleteModel(
            name='BakeryInventory',
        ),
        migrations.DeleteModel(
            name='DairyInventory',
        ),
        migrations.DeleteModel(
            name='FreshInventory',
        ),
        migrations.DeleteModel(
            name='GroceryInventory',
        ),
    ]
