# Generated by Django 4.0.6 on 2022-07-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_item_name_bakeryinventory_itemname_and_more'),
        ('sis_api', '0005_allinventory_delete_bakeryinventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allinventory',
            name='Bakery',
        ),
        migrations.AddField(
            model_name='allinventory',
            name='Bakery',
            field=models.ManyToManyField(blank=True, default='N/A', to='inventory.bakeryinventory'),
        ),
        migrations.RemoveField(
            model_name='allinventory',
            name='Dairy',
        ),
        migrations.AddField(
            model_name='allinventory',
            name='Dairy',
            field=models.ManyToManyField(blank=True, default='N/A', to='inventory.dairyinventory'),
        ),
        migrations.RemoveField(
            model_name='allinventory',
            name='Fresh',
        ),
        migrations.AddField(
            model_name='allinventory',
            name='Fresh',
            field=models.ManyToManyField(blank=True, default='N/A', to='inventory.freshinventory'),
        ),
        migrations.RemoveField(
            model_name='allinventory',
            name='Grocery',
        ),
        migrations.AddField(
            model_name='allinventory',
            name='Grocery',
            field=models.ManyToManyField(blank=True, default='N/A', to='inventory.groceryinventory'),
        ),
    ]
