# Generated by Django 4.0.6 on 2022-07-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sis_api', '0006_remove_allinventory_bakery_allinventory_bakery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allinventory',
            options={'verbose_name_plural': 'All Inventory'},
        ),
    ]
