# Generated by Django 4.0.6 on 2022-07-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_api', '0007_alter_allinventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinventory',
            name='All_Inventory_Last_Reset',
            field=models.DateField(auto_now=True),
        ),
    ]
