# Generated by Django 4.0.6 on 2022-07-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0012_alter_deliinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('All_Inventory_Last_Reset', models.DateField(auto_now=True)),
                ('Bakery', models.ManyToManyField(blank=True, default='N/A', to='inventory.bakeryinventory')),
                ('Dairy', models.ManyToManyField(blank=True, default='N/A', to='inventory.dairyinventory')),
                ('Fresh', models.ManyToManyField(blank=True, default='N/A', to='inventory.freshinventory')),
                ('Grocery', models.ManyToManyField(blank=True, default='N/A', to='inventory.groceryinventory')),
            ],
            options={
                'verbose_name_plural': 'All Inventory',
            },
        ),
    ]
